export const SET_JACKPOT_DATA = 'SET_JACKPOT_DATA';
export const SET_WINNING_PRIZE = 'SET_WINNING_PRIZE';

export const WINNING_PRIZE_CASH_IN_SUCCESS = 'WINNING_PRIZE_CASH_IN_SUCCESS';

export const SET_WIN_PRIZE_HISTORY = 'SET_WIN_PRIZE_HISTORY';

export const DISPLAY_WINNING_ANIMATION = 'DISPLAY_WINNING_ANIMATION';

// export const UPDATE_DISPLAY_WIN_PRIZE = 'UPDATE_DISPLAY_WIN_PRIZE';

export const REMOVE_DISPLAY_WINNING_ANIMATION =
  'REMOVE_DISPLAY_WINNING_ANIMATION';
