export const SET_JACKPOT_DATA = 'SET_JACKPOT_DATA';

export const SET_WINNING_PRIZE = 'SET_WINNING_PRIZE';
export const REMOVE_WIN_PRIZE_FROM_LIST = 'REMOVE_WIN_PRIZE_FROM_LIST';

export const SET_WIN_PRIZE_HISTORY = 'SET_WIN_PRIZE_HISTORY';

export const SET_DISPLAY_WIN_PRIZE = 'DISPLAY_WINNING_ANIMATION';
export const UPDATE_DISPLAY_WIN_PRIZE = 'UPDATE_DISPLAY_WIN_PRIZE';
export const REMOVE_DISPLAY_WIN_PRIZE = 'REMOVE_DISPLAY_WIN_PRIZE';

export const SET_WIN_RECORD_LIST = 'SET_WIN_RECORD_LIST';

export const UPDATE_WIN_PRIZE_LIST_CASH_IN_STATUS =
  'UPDATE_WIN_PRIZE_LIST_CASH_IN_STATUS';

export const SHOW_TOAST = 'SHOW_TOAST';

export const SET_SERVICE_BELL = 'SET_SERVICE_BELL';
export const REMOVE_SERVICE_BELL_FROM_LIST = 'REMOVE_SERVICE_BELL_FROM_LIST';
